### ISSUE TITLE
Istanbul Hardfork meta issue

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#1280]
List of EIPs that are highly favorable to be chosen as a part of Istanbul Hardfork:
- [ ]  [EIP 615](https://eips.ethereum.org/EIPS/eip-615): Subroutines and Static Jumps for the EVM 
- [ ]  [EIP 1057](https://eips.ethereum.org/EIPS/eip-1057): ProgPoW, a Programmatic Proof-of-Work 
- [ ]  [EIP 1829](https://eips.ethereum.org/EIPS/eip-1829): Precompile for Elliptic Curve Linear Combinations

**Comment by zilm13** [comment]
I'm starting EIP-1829
